"""Reports.

The business-facing artefact: an executive summary, the KPI picture, findings,
risk, quality and SQL verification, plus export. The page renders the *same*
report object a scheduled run would email, so what is previewed is what ships.
"""

from __future__ import annotations

import datetime as dt
from typing import Any, List

import pandas as pd
import streamlit as st

from components import cards, layout, tables
from styles.theme import COLORS

import insights as insight_adapters


def _build_context(ctx) -> Any:
    from src.reporting import ReportContext

    result = ctx.result
    retention = result.analyses.get("retention")
    segmentation = result.analyses.get("segmentation", {}) or {}
    answers = result.analyses.get("answers")
    answers_list = (
        [a for a in answers.to_dict("records")] if isinstance(answers, pd.DataFrame) else (answers or [])
    )
    return ReportContext(
        kpis=ctx.kpis,
        retention=retention.summary if retention else {},
        retention_comparison=retention.comparison if retention else pd.DataFrame(),
        segment_metrics=segmentation.get("metrics", pd.DataFrame()),
        segment_insight=segmentation.get("insight", ""),
        trend_summary=result.analyses.get("trend_summary", {}),
        monthly_trend=result.analyses.get("monthly_trend", pd.DataFrame()),
        engagement=result.analyses.get("engagement", {}),
        anomalies=result.analyses.get("anomalies", pd.DataFrame()),
        alerts=result.alerts,
        alert_summary=result.analyses.get("alert_summary", {}),
        quality=(result.quality or {}).get("summary", {}),
        quality_checks=(result.quality or {}).get("checks", pd.DataFrame()),
        crosscheck=result.validation.get("crosscheck", pd.DataFrame()),
        integrity=result.validation.get("integrity", pd.DataFrame()),
        answers=_hydrate_answers(answers_list),
        root_causes=result.analyses.get("root_cause_chains", []),
        integration=result.integration or {},
        funnel=result.analyses.get("platform_funnel", pd.DataFrame()),
        funnel_insight=result.analyses.get("funnel_insight", ""),
        sources=(result.metadata or {}).get("sources", {}),
        metadata=result.metadata or {},
        stage_records=result.stage_records,
    )


def _hydrate_answers(rows: List[dict]) -> list:
    """Rebuild lightweight answer objects from the stored answer table."""
    from dataclasses import dataclass, field

    @dataclass
    class _Answer:
        question_id: str
        question: str
        answer: str
        evidence: List[str] = field(default_factory=list)
        provenance: str = "real"
        caveats: List[str] = field(default_factory=list)
        available: bool = True

    hydrated = []
    for row in rows:
        if not isinstance(row, dict):
            hydrated.append(row)
            continue
        hydrated.append(
            _Answer(
                question_id=str(row.get("question_id", row.get("id", ""))),
                question=str(row.get("question", "")),
                answer=str(row.get("answer", "")),
                evidence=[item for item in str(row.get("evidence", "")).split(" | ") if item],
                provenance=str(row.get("provenance", "real")),
                caveats=[item for item in str(row.get("caveats", "")).split(" | ") if item],
                available=bool(row.get("available", True)),
            )
        )
    return hydrated


def render(ctx) -> None:
    result = ctx.result
    kpis = ctx.kpis
    quality = (result.quality or {}).get("summary", {}) or {}
    validation = (result.validation or {}).get("summary", {}) or {}
    alerts = result.analyses.get("alert_summary", {}) or {}
    segmentation = result.analyses.get("segmentation", {}) or {}

    layout.page_header(
        "Executive Report",
        "The board-ready summary: retention health, the findings behind it, risk, data quality and "
        "independent SQL verification. Generated by the analytical layer, not authored in the UI.",
        icon_name="description",
        eyebrow="Reporting",
    )

    _report_header(result, kpis, quality, validation, alerts)
    _key_findings(result)
    _section_summaries(kpis, segmentation, alerts, quality, validation)
    _generate_and_export(ctx, result)


# ---------------------------------------------------------------------------
def _report_header(result, kpis, quality, validation, alerts) -> None:
    layout.section(
        "Report snapshot",
        "Generated date, retention health and the state of every supporting layer at the time of this run.",
        icon_name="file-text",
    )
    left, right = st.columns([1, 2.4])
    with left:
        retention_rate = kpis.get("retention_rate")
        st.markdown(
            "".join(
                [
                    '<div class="fp-card" style="text-align:center;">',
                    cards.health_ring(retention_rate, caption="members retained"),
                    f'<div style="font-size:.78rem;color:{COLORS["muted"]};margin-top:.6rem;">'
                    f"Generated {dt.datetime.now().strftime('%d %b %Y')} · observation date "
                    f"{result.metadata.get('observation_date', 'n/a')}</div>",
                    "</div>",
                ]
            ),
            unsafe_allow_html=True,
        )
    with right:
        cards.kpi_row(
            [
                cards.Kpi(
                    "Members in scope",
                    kpis.get("total_members"),
                    icon="users",
                    provenance="real",
                    note="Membership source population",
                ),
                cards.Kpi(
                    "Churn rate",
                    kpis.get("churn_rate"),
                    unit="%",
                    icon="user-minus",
                    provenance="real",
                    tone="danger",
                    note="Real churn outcome",
                ),
                cards.Kpi(
                    "Data quality",
                    icon="database",
                    provenance="real",
                    status=str(quality.get("status", "n/a")),
                    note=f"{quality.get('passed', 0)} of {quality.get('total_checks', 0)} checks passed",
                ),
                cards.Kpi(
                    "SQL validation",
                    icon="terminal",
                    provenance="derived",
                    status=str(validation.get("status", "n/a")),
                    note=f"{validation.get('kpi_passed', 0)} of {validation.get('kpi_checks', 0)} KPIs verified in SQL",
                ),
            ],
            per_row=2,
        )
        cards.progress_line(
            "Retention rate",
            kpis.get("retention_rate"),
            color=COLORS["primary"],
            detail="Retained members divided by eligible members, from the source churn label",
        )
        cards.progress_line(
            "Validation pass rate",
            quality.get("pass_rate"),
            color=COLORS["info"],
            detail="Share of validation rules that passed in this run",
        )
        if alerts:
            layout.footnote(f"Risk posture: {alerts.get('status', 'n/a')} — {alerts.get('headline', '')}")


def _key_findings(result) -> None:
    layout.section(
        "Key findings",
        "The analytical questions this product answers, taken directly from the pipeline output.",
        icon_name="lightbulb",
    )
    available = insight_adapters.from_answers(result, limit=10)
    if available:
        numbered = "".join(
            f'<div style="display:flex;gap:.7rem;padding:.35rem 0;">'
            f'<span style="color:{COLORS["primary"]};font-weight:700;">{index}</span>'
            f'<span style="font-size:.88rem;color:{COLORS["text_secondary"]};">'
            f"<strong style='color:{COLORS['text']};'>{insight.title}</strong><br>{insight.body}</span></div>"
            for index, insight in enumerate(available, start=1)
        )
        st.markdown(f'<div class="fp-card">{numbered}</div>', unsafe_allow_html=True)
    else:
        cards.empty_state(
            "No findings available",
            "The analytical layer produced no publishable answers for this population.",
            icon_name="lightbulb",
        )

    unavailable = insight_adapters.unavailable_answers(result)
    if unavailable:
        with st.expander("Questions the available data cannot answer"):
            for question, answer in unavailable:
                st.markdown(f"**{question}**")
                st.markdown(f"{answer}")


def _section_summaries(kpis, segmentation, alerts, quality, validation) -> None:
    layout.section(
        "Section summaries",
        "Retention, engagement, segments, risk and quality — the same view the report body expands on.",
        icon_name="layout-dashboard",
    )
    left, right = st.columns(2)
    with left:
        cards.stat_block(
            "Retention",
            kpis.get("retention_rate"),
            unit="%",
            detail=f"Churn {kpis.get('churn_rate', 0):.2f}% · at-risk members {kpis.get('at_risk_members', 0):,}",
        )
        cards.stat_block(
            "Engagement",
            kpis.get("avg_visits_per_month"),
            unit="per_month",
            detail=f"Mean engagement score {kpis.get('avg_engagement_score', 0):.1f}/100",
        )
        cards.stat_block(
            "Platform activity",
            kpis.get("platform_events"),
            detail=f"Attendance rate {kpis.get('platform_attendance_rate', 0):.1f}%",
        )
    with right:
        cards.stat_block(
            "Segments",
            len(segmentation.get("metrics", pd.DataFrame())),
            detail=str(segmentation.get("insight", ""))[:120] + ("…" if segmentation.get("insight") else ""),
        )
        cards.stat_block(
            "Risk",
            alerts.get("total", 0),
            detail=f"Status {alerts.get('status', 'n/a')} · {alerts.get('high', 0)} high severity",
        )
        cards.stat_block(
            "Assurance",
            validation.get("status", "n/a"),
            detail=f"Data quality {quality.get('pass_rate', 0):.1f}% pass rate · "
            f"{validation.get('kpi_passed', 0)}/{validation.get('kpi_checks', 0)} KPIs verified in SQL",
        )


def _generate_and_export(ctx, result) -> None:
    from src.common.config import ARTIFACTS_DIR
    from src.reporting import generate_report, markdown_to_html, send_report

    layout.section(
        "Generate and export",
        "Rebuild the report from the current filters and thresholds, then export it in the format you need.",
        icon_name="download",
    )

    controls = st.columns([1, 1, 2])
    with controls[0]:
        generate = st.button("Generate report", type="primary", width="stretch")
    with controls[1]:
        include_email = st.checkbox("Include email status", value=False)

    if generate:
        with cards.loading("Rendering the report from the analytical layer..."):
            report = generate_report(_build_context(ctx), write=True)
        st.session_state["generated_report"] = report
        st.caption("Report regenerated from the current filters and thresholds.")

    report = st.session_state.get("generated_report")
    if report is None:
        if result.report_markdown:
            report = type("_R", (), {"markdown": result.report_markdown, "html": "", "path": None})()
            st.caption(
                "Showing the report produced by the last pipeline run. Press **Generate report** to "
                "rebuild it from the current filters."
            )
        else:
            cards.empty_state(
                "No report available",
                "The last pipeline run produced no report artefact.",
                icon_name="file-text",
                hint="Press **Generate report**, or run `python scripts/generate_report.py`.",
            )
            return

    downloads = st.columns(3)
    with downloads[0]:
        st.download_button(
            "Download markdown",
            data=report.markdown,
            file_name="fitpulse_executive_report.md",
            mime="text/markdown",
            width="stretch",
        )
    with downloads[1]:
        st.download_button(
            "Download HTML",
            data=report.html or markdown_to_html(report.markdown),
            file_name="fitpulse_executive_report.html",
            mime="text/html",
            width="stretch",
        )
    with downloads[2]:
        members = result.table("member_features")
        if not members.empty:
            st.download_button(
                "Download member features (CSV)",
                data=members.to_csv(index=False),
                file_name="member_features.csv",
                mime="text/csv",
                width="stretch",
            )

    with st.expander("Full report preview", expanded=False):
        st.markdown(report.markdown)

    if include_email:
        with st.expander("Email delivery configuration", expanded=True):
            from src.reporting import email_configured

            configured = email_configured()
            tables.key_value_table(
                [
                    ("Configuration", "complete" if configured else "not configured"),
                    ("Required variables", "FITPULSE_SMTP_HOST, FITPULSE_REPORT_FROM, FITPULSE_REPORT_TO"),
                    ("Credentials", "read from .env only; never logged"),
                    ("CLI equivalent", "python scripts/generate_report.py --email"),
                ],
                caption="Credentials come exclusively from environment variables and .env is git-ignored.",
            )
            if st.button("Check delivery configuration"):
                outcome = send_report(report, dry_run=True)
                st.caption(outcome.message)

    layout.section(
        "Reproduction",
        "Everything on this page can be regenerated from the command line.",
        icon_name="terminal",
    )
    st.code(
        "python scripts/pipeline.py        # ingest → analyse → SQL → alerts → report\n"
        "python scripts/generate_report.py # regenerate the report from stored artifacts\n"
        "pytest                            # unit, data and integration tests",
        language="bash",
    )
    layout.footnote(f"Artifacts are written to `{ARTIFACTS_DIR}`.")
