"""Regenerate ``app/components/icons.py`` from the Lucide icon set.

The dashboard uses one icon library only (Lucide, ISC licence) so that every
glyph in the product shares the same 24px grid, stroke weight and rounded
terminals. Icons are inlined as SVG so the dashboard renders identically with no
network access and no external font dependency.

Usage::

    python scripts/fetch_icons.py            # refresh from the pinned version
    python scripts/fetch_icons.py --check    # report missing icon names

Lucide: https://lucide.dev — ISC licensed (see NOTICE in the generated module).
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
TARGET = PROJECT_ROOT / "app" / "components" / "icons.py"
LUCIDE_VERSION = "0.454.0"
CDN = f"https://unpkg.com/lucide-static@{LUCIDE_VERSION}/icons/{{name}}.svg"

#: Every glyph the dashboard is allowed to use. Keeping the list closed stops
#: icon sprawl and guarantees the set stays visually consistent.
ICON_NAMES = (
    # navigation
    "layout-dashboard", "activity", "trending-up", "users", "shield-alert",
    "database", "terminal", "file-chart-column", "workflow", "settings", "server",
    "sliders-horizontal",
    # KPI / metrics
    "user-check", "user-minus", "percent", "dumbbell", "flame", "clock",
    "triangle-alert", "gauge", "target", "timer", "footprints", "heart-pulse",
    "calendar-check", "refresh-cw", "zap", "shield-check", "scale", "crosshair",
    "circle-dot",
    # status + feedback
    "circle-check", "circle-alert", "circle-x", "info", "arrow-up-right",
    "arrow-down-right", "minus", "chevron-right", "sparkles", "lightbulb",
    # controls + io
    "filter", "search", "download", "mail", "external-link", "play",
    "rotate-ccw", "upload", "eye", "bell",
    # content
    "table", "table-2", "code", "chart-pie", "chart-column", "chart-line",
    "file-text", "clipboard-check", "list-filter", "layers", "boxes", "compass",
    "award", "badge-check", "trophy", "medal", "ruler", "repeat", "flag", "star",
    "lock", "git-branch",    "building-2", "credit-card", "wallet", "calendar-days",
    "map-pin", "graduation-cap", "ban", "sunrise", "sun", "moon", "globe",
    "file-chart-line", "chart-no-axes-column", "list-checks", "circle-user",
    "shield-question", "square-activity",
)

TEMPLATE = '''"""Icon system — Lucide (ISC licence), inlined as SVG.

Generated by ``scripts/fetch_icons.py`` from Lucide v{version}.
Do not edit by hand: add names to ``ICON_NAMES`` in the fetch script and re-run.

Icons are inlined rather than loaded from a font or a CDN so the dashboard
renders identically offline. One library, one 24px grid, one stroke weight —
never emoji — is what keeps the interface visually coherent.
"""

from __future__ import annotations

from typing import Dict, Optional

LUCIDE_VERSION = "{version}"

#: Fallback used when an unknown icon name is requested, so a typo degrades to a
#: neutral glyph instead of breaking a page.
FALLBACK = "circle-dot"

_ICONS: Dict[str, str] = {{
{body}
}}


def available() -> tuple[str, ...]:
    """Sorted names of every icon in the registry."""
    return tuple(sorted(_ICONS))


def icon(
    name: str,
    size: int = 18,
    color: str = "currentColor",
    stroke_width: float = 1.75,
    extra_style: str = "",
) -> str:
    """Return one inline SVG icon.

    ``color`` defaults to ``currentColor`` so the glyph inherits the colour of
    the surrounding component instead of hard-coding a hex value.
    """
    body = _ICONS.get(name) or _ICONS[FALLBACK]
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{{size}}" height="{{size}}" '
        f'viewBox="0 0 24 24" fill="none" stroke="{{color}}" stroke-width="{{stroke_width}}" '
        f'stroke-linecap="round" stroke-linejoin="round" class="fp-icon" aria-hidden="true" '
        f'focusable="false" style="flex:0 0 auto;{{extra_style}}">{{body}}</svg>'
    )


def icon_chip(
    name: str,
    size: int = 18,
    color: str = "#22C55E",
    stroke_width: float = 1.75,
    tile: Optional[str] = None,
) -> str:
    """An icon inside a rounded tinted tile — the standard card leading glyph."""
    background = tile or _tint(color)
    return (
        f'<span class="fp-icon-tile" style="background:{{background}};color:{{color}};">'
        f'{{icon(name, size=size, color=color, stroke_width=stroke_width)}}</span>'
    )


def _tint(color: str, alpha: float = 0.14) -> str:
    """A translucent version of a hex colour, for icon tile backgrounds."""
    value = color.lstrip("#")
    if len(value) != 6:
        return "rgba(148,163,184,0.16)"
    try:
        red, green, blue = (int(value[i : i + 2], 16) for i in (0, 2, 4))
    except ValueError:
        return "rgba(148,163,184,0.16)"
    return f"rgba({{red}}, {{green}}, {{blue}}, {{alpha}})"


def serialize_registry() -> str:
    """Machine-readable registry (name -> inner SVG markup) for tests/tooling."""
    import json

    return json.dumps(_ICONS, indent=2, sort_keys=True)
'''


def fetch(name: str) -> str | None:
    request = urllib.request.Request(
        CDN.format(name=name), headers={"User-Agent": "fitpulse-icon-fetch"}
    )
    try:
        with urllib.request.urlopen(request, timeout=20) as response:  # noqa: S310
            markup = response.read().decode("utf-8")
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError):
        return None
    match = re.search(r"<svg[^>]*>(.*)</svg>", markup, flags=re.DOTALL)
    if not match:
        return None
    return " ".join(match.group(1).split())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="only report missing names")
    arguments = parser.parse_args()

    resolved: Dict[str, str] = {}
    missing: list[str] = []
    for name in ICON_NAMES:
        body = fetch(name)
        if body:
            resolved[name] = body
        else:
            missing.append(name)

    if arguments.check:
        print(f"resolved={len(resolved)} missing={missing}")
        return 0 if not missing else 1

    if not resolved:
        print("No icons could be downloaded; leaving the registry untouched.")
        return 1

    resolved.setdefault(FALLBACK_NAME, resolved.get("circle-check", "<circle cx='12' cy='12' r='9'/>"))
    body_lines = "\n".join(f'    "{name}": {body!r},' for name, body in sorted(resolved.items()))
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(
        TEMPLATE.format(version=LUCIDE_VERSION, body=body_lines), encoding="utf-8"
    )
    print(f"Wrote {TARGET.relative_to(PROJECT_ROOT)} with {len(resolved)} icons.")
    if missing:
        print(f"Skipped {len(missing)} unavailable names: {', '.join(missing)}")
    return 0


FALLBACK_NAME = "circle-dot"

if __name__ == "__main__":
    sys.exit(main())
