"""Cleaning: measurable, semantics-aware transformation of source data."""

from .cleaners import (
    CleaningResult,
    CleaningStep,
    PII_COLUMNS,
    OUTLIER_POTENTIAL_ERROR,
    OUTLIER_UNKNOWN,
    OUTLIER_VALID_EXTREME,
    add_age_group,
    add_missing_flags,
    age_group,
    clamp,
    classify_outliers,
    clean_null_strings,
    drop_exact_duplicates,
    drop_pii,
    impute_numeric_median,
    minmax_scale,
    normalize_boolean,
    normalize_category,
    outlier_summary,
    parse_time_of_day,
    safe_divide,
    strip_whitespace,
    to_datetime_safe,
    to_numeric_safe,
)
from .pipeline import (
    clean_activity_source,
    clean_membership_source,
    observation_date_from,
    ACTIVITY_NUMERIC_DOMAIN,
    MEMBERSHIP_NUMERIC_DOMAIN,
)

__all__ = [
    "CleaningResult",
    "CleaningStep",
    "PII_COLUMNS",
    "OUTLIER_POTENTIAL_ERROR",
    "OUTLIER_UNKNOWN",
    "OUTLIER_VALID_EXTREME",
    "add_age_group",
    "add_missing_flags",
    "age_group",
    "clamp",
    "classify_outliers",
    "clean_null_strings",
    "drop_exact_duplicates",
    "drop_pii",
    "impute_numeric_median",
    "minmax_scale",
    "normalize_boolean",
    "normalize_category",
    "outlier_summary",
    "parse_time_of_day",
    "safe_divide",
    "strip_whitespace",
    "to_datetime_safe",
    "to_numeric_safe",
    "clean_activity_source",
    "clean_membership_source",
    "observation_date_from",
    "ACTIVITY_NUMERIC_DOMAIN",
    "MEMBERSHIP_NUMERIC_DOMAIN",
]
