"""SQL layer: SQLite warehouse, query library execution, KPI cross-validation."""

from .database import (
    QUERY_MARKER,
    TableLoadReport,
    apply_schema,
    apply_views,
    connect,
    dataframe_to_sql_table,
    load_frame,
    load_tables,
    parse_named_queries,
    read_script,
    run_named_queries,
    run_query,
    run_script_library,
    scalar,
    table_columns,
)
from .crosscheck import (
    KPI_COMPARISONS,
    KpiComparisonSpec,
    STATUS_FAIL,
    STATUS_NA,
    STATUS_PASS,
    compare_kpis,
    compare_tables,
    integrity_checks,
    validation_summary,
)

__all__ = [
    "QUERY_MARKER",
    "TableLoadReport",
    "apply_schema",
    "apply_views",
    "connect",
    "dataframe_to_sql_table",
    "load_frame",
    "load_tables",
    "parse_named_queries",
    "read_script",
    "run_named_queries",
    "run_query",
    "run_script_library",
    "scalar",
    "table_columns",
    "KPI_COMPARISONS",
    "KpiComparisonSpec",
    "STATUS_FAIL",
    "STATUS_NA",
    "STATUS_PASS",
    "compare_kpis",
    "compare_tables",
    "integrity_checks",
    "validation_summary",
]
