"""Ingestion: load a dataset, detect its shape, map it onto the canonical model.

Two entry points are supported:

* **Reference contracts** — the two documented Kaggle datasets are described by
  :mod:`src.ingestion.schema` and loaded through :func:`load_sources`.
* **Any compatible export** — CSV/TXT/XLSX/XLS files are detected, mapped and
  renamed onto the canonical contract by :mod:`src.ingestion.mapping`
  (:func:`ingest_mapped_frame`, :func:`load_dataset_path`).

Both paths converge on the same canonical frames, so the analytics layer never
knows which dataset it is looking at.
"""

from .schema import (
    ACTIVITY_SOURCE,
    MEMBERSHIP_SOURCE,
    CANONICAL_FACT_WORKOUT,
    CANONICAL_DIM_MEMBER,
    CANONICAL_FACT_MEMBERSHIP,
    SourceSchema,
    get_source_schema,
    list_sources,
)
from .canonical import (
    CANONICAL_FIELDS,
    CanonicalField,
    ROLE_ACTIVITY,
    ROLE_MEMBERSHIP,
    ROLES,
    contract_names,
    contract_names_map,
    field_options_for_role,
    fields_for_role,
    get_field,
    required_fields_for_role,
)
from .loader import (
    IngestionError,
    SchemaMismatchError,
    SchemaReport,
    LoadedSource,
    SUPPORTED_SUFFIXES,
    detect_encoding,
    inspect_source_schema,
    load_activity_source,
    load_csv_robust,
    load_dataset_path,
    load_membership_source,
    load_sources,
    map_to_canonical,
    preview,
    read_tabular_bytes,
    frame_from_upload,
    ingest_mapped_frame,
    reference_source,
    validate_file,
    reader_from_upload,
    download_kaggle_source,
    missing_source_files,
    attempt_source_download,
)
from .mapping import (
    CAPABILITY_LABELS,
    HIGH,
    MEDIUM,
    LOW,
    NONE,
    CONFIDENCE_LABEL,
    CanonicalMapping,
    Capability,
    ColumnEvidence,
    ColumnMatch,
    CompatibilityReport,
    RoleDetection,
    assess_compatibility,
    apply_dual_source_capabilities,
    build_loaded_source,
    capability_frame,
    capability_map,
    column_evidence,
    contract_frame,
    describe_dataset,
    detect_role,
    merge_capabilities,
    member_key_repeatable,
    normalize_key,
    resolve_boolean,
    role_label,
    suggest_mapping,
    unavailable_capabilities,
)

__all__ = [
    # reference contracts
    "ACTIVITY_SOURCE",
    "MEMBERSHIP_SOURCE",
    "CANONICAL_FACT_WORKOUT",
    "CANONICAL_DIM_MEMBER",
    "CANONICAL_FACT_MEMBERSHIP",
    "SourceSchema",
    "get_source_schema",
    "list_sources",
    # canonical model
    "CANONICAL_FIELDS",
    "CanonicalField",
    "ROLE_ACTIVITY",
    "ROLE_MEMBERSHIP",
    "ROLES",
    "contract_names",
    "contract_names_map",
    "field_options_for_role",
    "fields_for_role",
    "get_field",
    "required_fields_for_role",
    # loading
    "IngestionError",
    "SchemaMismatchError",
    "SchemaReport",
    "LoadedSource",
    "SUPPORTED_SUFFIXES",
    "detect_encoding",
    "inspect_source_schema",
    "load_activity_source",
    "load_csv_robust",
    "load_dataset_path",
    "load_membership_source",
    "load_sources",
    "map_to_canonical",
    "preview",
    "read_tabular_bytes",
    "frame_from_upload",
    "ingest_mapped_frame",
    "reference_source",
    "validate_file",
    "reader_from_upload",
    "download_kaggle_source",
    "missing_source_files",
    "attempt_source_download",
    # mapping / capabilities
    "CAPABILITY_LABELS",
    "HIGH",
    "MEDIUM",
    "LOW",
    "NONE",
    "CONFIDENCE_LABEL",
    "CanonicalMapping",
    "Capability",
    "ColumnEvidence",
    "ColumnMatch",
    "CompatibilityReport",
    "RoleDetection",
    "assess_compatibility",
    "apply_dual_source_capabilities",
    "build_loaded_source",
    "capability_frame",
    "capability_map",
    "column_evidence",
    "contract_frame",
    "describe_dataset",
    "detect_role",
    "merge_capabilities",
    "member_key_repeatable",
    "normalize_key",
    "resolve_boolean",
    "role_label",
    "suggest_mapping",
    "unavailable_capabilities",
]
